[project]
name = "esp32-udp-screen-share-client"
version = "0.0.6"
description = "ESP32 专用屏幕共享 UDP 推流客户端"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mss",
    "numpy",
    "opencv-python",
    "pywin32; sys_platform == 'win32'",
    "pyyaml",
    "sounddevice",
]

[tool.uv]
package = false
